export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  SOCIAL_SIGNUP: '/social-signup',
  FIND_ACCOUNT: '/find-account',
  VERIFY_EMAIL: '/verify-email',
  PASSWORD: '/password',
  HOME: '/',
  POST_DETAIL: (id: number | string) => `/detail/${id}`,
  POST_WRITE: '/write',
  POST_EDIT: (id: number | string) => `/edit/${id}`,
  PROFILE: '/edit-profile',
  USER_PROFILE: (id: number | string) => `/user-profile/${id}`,
  NOTIFICATIONS: '/notifications',
  DM: '/dm',
  WIKI: '/wiki',
  WIKI_WRITE: '/wiki/write',
  WIKI_EDIT: (slug: string) => `/wiki/edit/${slug}`,
  WIKI_DETAIL: (slug: string) => `/wiki/${slug}`,
  WIKI_HISTORY: (slug: string) => `/wiki/${slug}/history`,
  WIKI_REVISION: (slug: string, n: number) => `/wiki/${slug}/revisions/${n}`,
  WIKI_DIFF: (slug: string) => `/wiki/${slug}/diff`,
  PACKAGES: '/packages',
  PACKAGE_WRITE: '/packages/write',
  PACKAGE_EDIT: (id: number) => `/packages/edit/${id}`,
  PACKAGE_DETAIL: (id: number) => `/packages/${id}`,
  ADMIN: '/admin',
  ADMIN_REPORTS: '/admin/reports',
  MY_ACTIVITY: '/my-activity',
  BADGES: '/badges',
} as const;
